import type { Category } from "./types";

export const CATEGORIES: Category[] = [
  {
    slug: "auto-elektricar",
    name: "Auto-električar",
    plural: "Auto-električari",
    iconKey: "auto-elektricar",
    metaDescription: "Auto-električari u Novom Sadu — dijagnostika, alternator, akumulator, instalacija.",
    description: "Moderna vozila su puna elektronike — od akumulatora i alternatora do desetina senzora i ECU modula koji upravljaju motorom, menjačem i sistemima bezbednosti. Auto-električar u Novom Sadu rešava kvarove koje obični mehaničar ne može ni da dijagnostikuje.\n\nAuto-električari s MajstoriNS rade: kompjutersku dijagnostiku svih sistema i brisanje grešaka, zamenu i testiranje akumulatora i startnih baterija, popravku i remont alternatora i startera, ugradnju auto-radija, navigacije, kamera za vožnju unazad i parking senzora, popravku auto-rasvete — far, stop, smerovi, dnevna svetla, LED konverzija, popravku elektro podizača stakla, centralnog zaključavanja i alarmnih sistema, ugradnju auto-grejača i daljinskog starta.\n\nRade za sve marke vozila — domaća i strana — u Novom Sadu i okolini: Liman, Detelinara, Telep, Novo naselje, Centar, Podbara, Salajka, Klisa, Adice, Petrovaradin, Sremska Kamenica, Veternik i Futog.",
  },
  {
    slug: "automehanicar",
    name: "Automehaničar",
    plural: "Automehaničari",
    iconKey: "automehanicar",
    metaDescription: "Automehaničari u Novom Sadu — servis, popravka motora, dijagnostika.",
    description: "Kada automobil pokaže znakove kvara — neobičan zvuk, upozorenje na instrument tabli, otežano paljenje ili slab rad motora — pravi automehaničar u Novom Sadu može da reši problem brzo i bez nepotrebnih troškova. Na MajstoriNS naći ćete proverene automehaničare koji rade servis svih vrsta automobila: menjanje ulja i filtera, zamena kočnica i diskova, kompjuterska dijagnostika grešaka, popravka menjača i motora, zamena amortizera, kvačila i zupčastog kaiša, servis klima sistema i rashladnog sistema.\n\nAutomehaničari iz naše baze rade sa domaćim i stranim vozilima — Volkswagen, BMW, Mercedes, Opel, Renault, Peugeot, Ford, Toyota, Škoda, Fiat i ostale marke. Mnogi nude dolazak na teren ili pomoć na putu za hitne situacije.\n\nPronađite automehaničara u svom delu Novog Sada: Liman, Detelinara, Novo naselje, Telep, Centar, Podbara, Salajka, Klisa, Adice — kao i u Petrovaradinu, Sremskoj Kamenici, Vetrniku i Futogu. Dogovorite termin direktno, bez posrednika.",
  },
  {
    slug: "bravar",
    name: "Bravar",
    plural: "Bravari",
    iconKey: "bravar",
    metaDescription: "Bravari u Novom Sadu — ograde, kapije, brave, hitno otvaranje vrata.",
    description: "Pokvarena brava, iskrivljena kapija, ograda koja treba popravku ili hitna zamena cilindra — bravar u Novom Sadu dolazi brzo i rešava problem na licu mesta.\n\nBravari s MajstoriNS obavljaju: hitno otvaranje vrata bez loma (stanovi, kuće, poslovni prostori, automobili), zamenu brava i cilindara, ugradnju sigurnosnih brava klase A i B, ugradnju blindovanih i protivprovalnih vrata, izradu i montažu ograda, kapija i portala od metala i nerđajućeg čelika, zavarivanje metalnih konstrukcija i nadstrešnica, ugradnju rešetki za prozore, bezbednosnih mreža i zaštitnih vrata.\n\nDostupni za hitne intervencije i planirane radove u Novom Sadu: Centar, Liman, Detelinara, Telep, Novo naselje, Podbara, Salajka, Klisa, Adice, Petrovaradin, Sremska Kamenica, Veternik i Futog.",
  },
  {
    slug: "elektricar",
    name: "Električar",
    plural: "Električari",
    iconKey: "elektricar",
    metaDescription: "Električari u Novom Sadu — instalacije, kvarovi, rasveta, ormari.",
    description: "Električna instalacija u kući ili poslovnom prostoru nije nešto s čim se eksperimentiše. Pravi električar u Novom Sadu zna da uradi posao bezbedno i po propisima — od zamene osigurača do kompletne rekonstrukcije razvoda.\n\nElektričari s MajstoriNS rade: postavljanje i rekonstrukciju elektro instalacija, ugradnju rasvete, lusteri, LED traka i spoljne rasvete, zamenu osigurača i razvodnih ormara, postavljanje utičnica i prekidača, ugradnju zaštitnih FID prekidača i uzemljenja, popravku kvarova na kućnoj instalaciji, instalaciju video nadzora i interfona, ugradnju električnih podnih grejanja, priključak na niskonaponsku mrežu.\n\nDostupni za stanove, kuće i poslovne objekte u svim delovima Novog Sada: Liman, Centar, Detelinara, Telep, Novo naselje, Podbara, Salajka, Klisa, Adice — i u okolnim mestima: Petrovaradin, Sremska Kamenica, Veternik, Futog. Hitne intervencije dostupne i van radnog vremena.",
  },
  {
    slug: "gradjevinar",
    name: "Građevinski radovi",
    plural: "Građevinari",
    iconKey: "gradjevinar",
    metaDescription: "Građevinski radovi u Novom Sadu — adaptacije, zidanje, malterisanje, betoniranje.",
    description: "Adaptacija stana, rušenje pregradnih zidova, dogradnja kuće, malterisanje ili kompletna rekonstrukcija — građevinar u Novom Sadu koordinira radove i obezbeđuje da sve bude urađeno solidno i po propisima.\n\nGrađevinari s MajstoriNS izvode: adaptacije i rekonstrukcije stanova i kuća, rušenje i zidanje pregradnih zidova od opeke, ytonga i šuplje cigle, malterisanje mašinski i ručno, rigips i pregradne sisteme od suve gradnje, betoniranje temelja, ploča i stepenica, armiranje i oplatu, postavljanje termičke fasade (stiropur sistem), izgradnju garaža, nadstrešnica i pomoćnih objekata, nivelaciju podova samonivelirajućim masama, hidroizolaciju podruma i temelja.\n\nDostupni za sve vrste objekata u Novom Sadu — Centar, Liman, Detelinara, Telep, Novo naselje, Podbara, Salajka, Klisa, Adice — i u okolnim mestima: Petrovaradin, Sremska Kamenica, Veternik, Futog i okolna sela.",
  },
  {
    slug: "keramicar",
    name: "Keramičar",
    plural: "Keramičari",
    iconKey: "keramicar",
    metaDescription: "Keramičari u Novom Sadu — postavljanje pločica, kupatila, terase.",
    description: "Postavljanje pločica zahteva preciznost — loše postavljen keramičar ostavlja neravne fugne, napukle ploče i curenje ispod obloge. Provereni keramičar u Novom Sadu radi uredno, sa pravilnom pripremom podloge i vodonepropusnom zaštitom pre postavljanja.\n\nKeramičari s MajstoriNS postavljaju: pločice u kupatilu, toaletu i kuhinjskom prostoru, podne pločice u hodniku, dnevnoj sobi i na terasi, fasadne pločice i klinker, keramiku na stepenicama i podestima, mozaik i dekorativne obloge, spoljne pločice otporne na mraz. Rade i demontažu stare keramike, nivelaciju podloge sa samonivelirajućim masama, fugiranje i silikonisanje spojeva.\n\nPronađite keramičara u svom kvartu: Liman, Centar, Detelinara, Telep, Novo naselje, Podbara, Salajka, Klisa, Adice — kao i u Petrovaradinu, Sremskoj Kamenici, Vetrniku i Futogu.",
  },
  {
    slug: "krovopokrivac",
    name: "Krovopokrivač",
    plural: "Krovopokrivači",
    iconKey: "krov",
    metaDescription: "Krovopokrivači u Novom Sadu — postavljanje crepa, lima, sanacija krovova.",
    description: "Propušten krov je problem koji samo vremenom postaje gori. Krovopokrivač u Novom Sadu može da locira i popravi curenje pre nego što dođe do veće štete na konstrukciji ili enterijer.\n\nKrovopokrivači s MajstoriNS rade: postavljanje i zamenu crijepa — keramičkog, betonskog i mediteran, limene krovove od pocinkovanog i obojenog lima, ravne krovove sa bitumenskim trakama i EPDM membranom, ugradnju termoizolacije i hidroizolacije krovova, postavljanje oluka i odvodnih cevi, montažu krovnih prozora i svetlarnika, krpljenje i sanaciju propuštenih mesta, antikorozivnu zaštitu metalnih krovova, ugradnju snegobrana.\n\nRade na porodičnim kućama, višeporodičnim objektima i privrednim halama u Novom Sadu i okolini: Petrovaradin, Sremska Kamenica, Veternik, Futog i okolna sela.",
  },
  {
    slug: "limar",
    name: "Limar",
    plural: "Limari",
    iconKey: "limar",
    metaDescription: "Limarski radovi u Novom Sadu — krovovi, oluci, opšivke. Pronađi proverenog limara u svom kraju.",
    description: "Limarski radovi su često zanemareni dok ne nastane problem — propušten oluk, oštećena opšivka ili krovni lim koji popušta u prvoj kiši.\n\nLimari s MajstoriNS rade: ugradnju i popravku oluka i odvodnih cevi od lima i PVC-a, limene opšivke dimnjaka, krovnih prodora i zabatnih zidova, ravne krovove od pocinkovanog i poliesterskog lima, fasadne obloge od aluminijuma i čelika, žljebove i odvodnike za terasu i balkon, krovne poklopce i ventilacione kape, antikorozivno farbanje starih limenih površina, ugradnju snegobrana i stepenica za krov.\n\nDostupni za porodične kuće, stanove i poslovne objekte u Novom Sadu i okolnim mestima: Centar, Liman, Detelinara, Telep, Petrovaradin, Sremska Kamenica, Veternik, Futog.",
  },
  {
    slug: "moler",
    name: "Moler-farbar",
    plural: "Moleri",
    iconKey: "moler",
    metaDescription: "Moleri u Novom Sadu — krečenje, gletovanje, dekorativni radovi.",
    description: "Svež sloj boje ili glet može potpuno promeniti izgled prostorije. Dobar moler u Novom Sadu ne radi samo krečenje — priprema površine, špatla, gruntuje i ostavlja ravne, čiste završetke bez vidljivih tragova.\n\nMoleri sa MajstoriNS rade: gletovanje i poravnanje zidova i plafona, krečenje disperzivnom i silikonskom bojom, farbanje fasada i spoljnih zidova, dekorativne tehnike — venecijaner, strukturalni malter, beton efekat, pranje, teksture, tapetiranje zidova, beljenje podruma i pomoćnih prostorija, antikorozivno farbanje metala i ograde, farbanje radijatora i grejnih tela.\n\nDostupni za adaptacije stanova, kuća i poslovnih prostora u svim novosadskim kvartovima: Centar, Liman, Detelinara, Podbara, Telep, Novo naselje, Salajka, Klisa, Adice — kao i u Petrovaradinu, Sremskoj Kamenici, Vetrniku i Futogu.",
  },
  {
    slug: "parketar",
    name: "Parketar",
    plural: "Parketari",
    iconKey: "parketar",
    metaDescription: "Parketari u Novom Sadu — postavljanje, hoblovanje, lakiranje parketa.",
    description: "Parket koji škripi, gubi boju ili ima oštećenja može se obnoviti bez kompletne zamene. Dobar parketar u Novom Sadu proceniće stanje poda i preporučiti pravo rešenje — sanaciju ili novo postavljanje.\n\nParketari s MajstoriNS postavljaju i obnavljaju: masivni hrast, bukvu i egzotične vrste, višeslojni i industrijski parket, laminat i vinilne podove, brodski pod u različitim formatima, mozaik parket i šahovska polja. Rade hoblovanje i brušenje starog parketa, lakiranje vodenim i uljnim lakovima, olejovanje i voskovanje, krpljenje oštećenih dasaka i zamenu pojedinih elemenata.\n\nDostupni za stanove, kuće i poslovne prostore u Novom Sadu: Liman, Centar, Detelinara, Telep, Novo naselje, Podbara, Salajka, Klisa, Adice — i u Petrovaradinu, Sremskoj Kamenici, Vetrniku i Futogu.",
  },
  {
    slug: "roletar",
    name: "Roletar",
    plural: "Roletari",
    iconKey: "roletar",
    metaDescription: "Roletari u Novom Sadu — popravka i ugradnja roletni, komarnika, venecijanera.",
    description: "Pokvarena roletna, popuštena opruga, traka koja je iskočila iz vođica ili motor koji ne reaguje — roletar u Novom Sadu može da popravi bez vađenja cele konstrukcije, direktno na prozoru.\n\nRotetari s MajstoriNS rade: popravku i zamenu PVC i aluminijumskih traka, opruga i navijača roletni, servis i zamenu elektromotora za roletne, ugradnju novih aluminijumskih i PVC roletni sa kutijom ili bez, ugradnju komarnika — fiksnih, uvlačnih i plisea, montažu venecijanera — aluminijumskih i drvenih, ugradnju tenda i nadstrešnica, popravku garnitura i zavesnih šina.\n\nDostupni za stanove, kuće i poslovne prostore u Novom Sadu: Centar, Liman, Detelinara, Telep, Novo naselje, Podbara, Salajka, Klisa, Adice — i u Petrovaradinu, Sremskoj Kamenici, Vetrniku i Futogu.",
  },
  {
    slug: "servis-bele-tehnike",
    name: "Servis bele tehnike",
    plural: "Servisi bele tehnike",
    iconKey: "bela-tehnika",
    metaDescription: "Servis bele tehnike u Novom Sadu — veš mašine, frižideri, šporeti.",
    description: "Pokvarena veš mašina, frižider koji ne hladi ili šporet koji ne pali — servis bele tehnike u Novom Sadu može da reši kvar bez kupovine novog aparata, često po ceni daleko manjoj od nove bele tehnike.\n\nServiseri s MajstoriNS popravljaju: veš mašine — pumpe, grejače, četkice motora, ležajeve bubnja i elektronske module, sušare za veš, frižidere i zamrzivače — kompresore, termostate, grijače odleđivanja, sudopere — pumpe i grejače, šporete i električne rerne — grejači, termostati, pečenje, mašine za sudove — pumpe i programatori. Dolaze na kućnu adresu i rade sa svim markama: Gorenje, Beko, Indesit, Whirlpool, Bosch, Samsung, LG, Electrolux, Candy.\n\nPokrivaju ceo Novi Sad: Centar, Liman, Detelinara, Telep, Novo naselje, Podbara, Salajka, Klisa, Adice, Petrovaradin, Sremska Kamenica, Veternik, Futog.",
  },
  {
    slug: "klima-servis",
    name: "Servis klima uređaja",
    plural: "Servisi klima uređaja",
    iconKey: "klima",
    metaDescription: "Servis i ugradnja klima uređaja u Novom Sadu — punjenje gasa, čišćenje, popravke.",
    description: "Klima uređaj koji ne hladi dovoljno, pravi neobičan zvuk, kaplje vodu ili se isključuje sam nije samo neugodan — može da napravi štetu u prostoru ili da troši duplo više struje nego što treba.\n\nServiseri klima uređaja s MajstoriNS rade: punjenje freona (R32, R410A, R22), čišćenje filtera i lamela unutrašnje i spoljne jedinice, dijagnostiku i popravku kvarova na kompresorima, pločama i ventilima, ugradnju novih inverter klima uređaja — Mitsubishi, Daikin, Gree, Fujitsu, LG, Samsung, Vivax, demontažu starih aparata, postavljanje spoljnih jedinica na fasade i krovove, servis kanalnih i kasetonskih sistema.\n\nDostupni za stanove, kuće, poslovne prostore i hale u svim delovima Novog Sada: Centar, Liman, Detelinara, Telep, Novo naselje, Podbara, Salajka, Klisa, Adice, Petrovaradin, Sremska Kamenica, Veternik, Futog.",
  },
  {
    slug: "staklorezac",
    name: "Staklorezac",
    plural: "Staklorezci",
    iconKey: "staklorezac",
    metaDescription: "Staklorezci u Novom Sadu — staklo po meri, ogledala, ulasci, zamena stakla.",
    description: "Puklo staklo na prozoru ili balkonskim vratima, ogledalo po meri, staklena pregrada između prostorija, vitrina za radnju ili tuševi od kaljenog stakla — staklorezac u Novom Sadu seče i ugrađuje staklo brzo i precizno.\n\nStaklorezci s MajstoriNS rade: zamenu razbijenog stakla na prozorima, balkonskim i unutrašnjim vratima, sečenje stakla po meri za nameštaj, police i satlike, ogledala u svim dimenzijama, staklene pregrade i tuševe od kaljenog stakla, izloge i vitrine za radnje i ordinacije, sigurnosno laminatno staklo, matiranje stakla i folije za privatnost, ugradnju staklenih vrata i kliznih sistema.\n\nDostupni u Novom Sadu i okolini: Centar, Liman, Detelinara, Telep, Novo naselje, Podbara, Petrovaradin, Sremska Kamenica, Veternik, Futog.",
  },
  {
    slug: "stolar",
    name: "Stolar",
    plural: "Stolari",
    iconKey: "stolar",
    metaDescription: "Stolarske usluge u Novom Sadu — nameštaj po meri, vrata, prozori, kuhinje.",
    description: "Drvo je materijal koji zahteva iskustvo i preciznost — od izrade nameštaja po meri do ugradnje vrata i prozora. Stolar u Novom Sadu može da reši i mali popravak i kompletan enterijer.\n\nStolari s MajstoriNS rade: izradu kuhinja po meri, plakara i garderobera, ugradnju unutrašnjih i spoljnih vrata i prozora, popravku i restauraciju starog nameštaja, izradu stepenica i ograda od drveta, postavljanje laminata, brodskog poda i masivnog parketa, montažu gotovog nameštaja iz prodavnica, izradu polica, klupa i vrtnog nameštaja. Rade sa hrastom, bukvom, borom, MDF-om i iverom.\n\nDostupni u Novom Sadu — Centar, Liman, Detelinara, Telep, Novo naselje, Podbara, Salajka, Klisa, Adice — i u okolini: Petrovaradin, Sremska Kamenica, Veternik, Futog.",
  },
  {
    slug: "tapetar",
    name: "Tapetar",
    plural: "Tapetari",
    iconKey: "tapetar",
    metaDescription: "Tapetari u Novom Sadu — presvlačenje nameštaja, tapaciranje, popravke.",
    description: "Presvlačenje fotelje, ugaone garniture ili sedišta za auto — tapetar u Novom Sadu može da obnovi nameštaj koji izgleda pohabano ali je strukturno ispravan, po ceni daleko manjoj od novog.\n\nTapetari s MajstoriNS rade: presvlačenje sofi, fotelja, trpezarijskih stolica i ugaonih garnitura — tkaninom, eko kožom i prirodnom kožom, tapaciranje uzglavlja, kreveta i sedišta po meri, auto tapacirung — sedišta, vrata i plafona, popravku i zamenu unutrašnjih opruga i pene, izradu jastuka, navlaka i sedišnih obloga, presvlačenje stolica za restorane i hotele, popravku oštećenih uglova i šavova. Rade u radionici uz besplatan transport nameštaja ili dolaze na adresu.\n\nDostupni u Novom Sadu i okolnim mestima: Petrovaradin, Sremska Kamenica, Veternik, Futog.",
  },
  {
    slug: "vodoinstalater",
    name: "Vodoinstalater",
    plural: "Vodoinstalateri",
    iconKey: "vodoinstalater",
    metaDescription: "Vodoinstalateri u Novom Sadu — popravke, odgušenja, kupatila. Hitne intervencije.",
    description: "Curenje vode, začepljenje odvoda, kvar na bojleru ili potreba za rekonstrukcijom kupatila — vodoinstalater je zanat koji često treba hitno. Na MajstoriNS naći ćete vodoinstalatera u Novom Sadu koji može da odreaguje brzo, bez čekanja po nekoliko dana.\n\nVodoinstalateri iz naše baze obavljaju: otklanjanje curenja na cevima, spojevima i slavinama, odgušenje odvoda i kanalizacije, ugradnju i servis bojlera i protočnih grejača, zamenu vodovodnih cevi (PVC, PPR, bakar), instalaciju sanitarija i armatora, rekonstrukciju i adaptaciju kupatila, priključak na gradsku vodovodnu i kanalizacionu mrežu, postavljanje podnog grejanja.\n\nDostupni za hitne intervencije i planirane radove u svim novosadskim kvartovima: Centar, Liman, Podbara, Detelinara, Telep, Novo naselje, Salajka, Klisa, Adice — kao i u Petrovaradinu, Sremskoj Kamenici, Vetrniku i Futogu.",
  },
  {
    slug: "vulkanizer",
    name: "Vulkanizer",
    plural: "Vulkanizeri",
    iconKey: "vulkanizer",
    metaDescription: "Vulkanizeri u Novom Sadu — zamena guma, centriranje, balansiranje.",
    description: "Probušena guma usred Novog Sada, sezonska zamena letnje na zimsku (ili obrnuto), centriranje točka posle udara u rupu — vulkanizer radi brzo jer zna da vreme i bezbednost nisu za čekanje.\n\nVulkanizeri s MajstoriNS rade: zamenu i popravku probušenih guma (zalivanje i krpljenje), montažu i demontažu guma sa felgama (čeličnim i aluminijumskim), centriranje i balansiranje točkova, TPMS servis — senzori pritiska u gumama, čuvanje i skladištenje sezonskih guma, prodaju novih i polovnih guma svih dimenzija, popravku i farbanje aluminijumskih felgi.\n\nDostupni za putnička vozila, kombije i laka teretna vozila u svim delovima Novog Sada: Centar, Liman, Detelinara, Telep, Novo naselje, Podbara, Salajka, Klisa, Adice, Petrovaradin, Sremska Kamenica, Veternik, Futog.",
  },
];

export function getCategoryBySlug(slug: string): Category | undefined {
  return CATEGORIES.find((c) => c.slug === slug);
}
